#!/usr/local/bin/php
<?php

/*
 * Copyright (C) 2023 Franco Fichtner <franco@opnsense.org>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

require_once 'script/load_phalcon.php';

$api = new OPNsense\Auth\API();

switch ($argv[1]) {
    case '-c':
        $username = get_arg(2, 'username');

        $res = $api->createKey($username);
        echo json_encode($res);

        break;

    case '-d':
        $username = get_arg(2, 'username');
        $apikey = get_arg(3, 'apikey');

        $res = $api->dropKey($username, $apikey);
        if (!$res) {
            echo "apikey not found\n";
            exit(1);
        }
        break;

    default:
        echo "Usage: opnsense-apikey -c username\n";
        echo "                       -d username apikey\n";
        exit(1);
}

function get_arg($num, $name)
{
    global $argv;

    $value = $argv[$num] ?? '';
    if ('' == $value) {
        echo 'No '.$name." given.\n";
        exit(1);
    }

    return trim($value,'\'"');
}

exit(0);
